### PR TITLE
Including translation of Brazilian Portuguese Reactive Manifesto

### PR DESCRIPTION
**Pull request by igorcosta**
Joining the reactive manifesto down here in Brazil.

### CODE REVIEW

**Comment by jboner** [comment]
Thanks a lot. Great job.

**Comment by rasummer** [comment]
Hi @igorcosta  I'm getting ready to add your translation to the Reactive Manifesto website. Could I ask you to translate a small amount of UI elements as well. You can find the phrases that need translation in the following google doc spread sheet: https://docs.google.com/spreadsheets/d/1Z_rA48AWXa1SjyR2n-vGqRKpGk124LtfdbpAOG-38cU/edit?usp=sharing

king regards

Richard

**Comment by igorcosta** [comment]
Hi there Richard


Here's the translations, couldn't edit the document.

Published on September 16 2014. (v2.0)Hello $x.Add your signatureThank you!
And spread the word!Remove your signatureHi there, You need to be logged to
sign the manifestoSign In with $xSign the manifestoLoadingGlossaryDownload
as PDFSuggest improvements$x people already signedFull listLogoutBack
To TopTable
of ContentsSearchGo back to the manifestoSignaturesFetch moreRibbonsShow
your support!

Publicado em 16 de Setembro de 2014. (v2.0)Olá $x.Adicione sua assinatura
Obrigado!  E espalhe a notícia para o mundo!Remover sua assinatura
Olá, Você precisa estar conectado para assinar o manifestoEntrar com $xAssinar
o manifestoCarregandoGlosárioBaixar como PDF
Sugira melhorias$x pessoas já assinaram o manifesto
List completa
SairVoltar ao topo
Tabela de conteúdoPesquisar
Voltar para o manifestoAssinaturasCarregar mais
FitasMostre seu suporte!


2015-04-08 14:54 GMT-03:00 Richard Summerhayes <notifications@github.com>:

> Hi @igorcosta <https://github.com/igorcosta> I'm getting ready to add
> your translation to the Reactive Manifesto website. Could I ask you to
> translate a small amount of UI elements as well. You can find the phrases
> that need translation in the following google doc spread sheet:
> https://docs.google.com/spreadsheets/d/1Z_rA48AWXa1SjyR2n-vGqRKpGk124LtfdbpAOG-38cU/edit?usp=sharing
>
> king regards
>
> Richard
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactivemanifesto/reactivemanifesto/pull/43#issuecomment-90987628>
> .
>



-- 

-----------------------------------
*Igor Costa*

*skype:igorpcosta*www.riacycle.com
*+55(11)3042-6276*
*+55(87)3861-8587*

**Comment by igorcosta** [comment]
@rasummer It didn't work quite well over commenting here. I guess I need to access the docs to properly works.

**Comment by igorcosta** [comment]
@rasummer Cool, just did it!

**Pull request merged**
