### PR TITLE
add chinese translation

### PR DESCRIPTION
**Pull request by zzz6519003**
:beer:

### CODE REVIEW

**Comment by jboner** [comment]
Thanks. How is this different from https://github.com/reactivemanifesto/reactivemanifesto/pull/74?

**Comment by pimgeek** [comment]
@jboner Maybe people just want to share this manifesto in Chinese as soon as possible, so they simply do it with out double-checking. However, if your team merged #74 earlier, @zzz6519003 would have noticed that there **was already a Chinese version**. :-)

**Comment by pimgeek** [comment]
@jboner Maybe people just want to share this manifesto in Chinese as soon as possible, so they simply translate it again with out double-checking. However, if your team merged #74 earlier, @zzz6519003 would have noticed that there **was already a Chinese version**. :-)

**Comment by zzz6519003** [comment]
acknowledged! your one is better than mine! I didn't see link on the official site so make a duplicate one.

plan to make a meteor site to solve this kind of thing XD

**Comment by pimgeek** [comment]
@zzz6519003 Oh, please keep your translation in your Github for **potential merge request** in the future, I think your translation may have some advantage. Since you seem to work in Microsoft, I suppose you have better sense on how to translate some special term. (I'm currently a product research/pre-sales staff in a web-startup company, so ....)

**Comment by jboner** [comment]
I apologize that we have not merged it, and that that caused you unnecessary work. We will try to do so ASAP. /cc @rasummer

**Comment by pimgeek** [comment]
@jboner Glad to hear that~ :+1:

**Comment by zzz6519003** [comment]
we are china... so many chinese, thoughtwork china have done the translation actually XD

**Comment by zzz6519003** [comment]
what about combining our work? use my README.zh-CN.md plus your glossary?

**Comment by pimgeek** [comment]
我们也翻译了 readme.md 部分，我建议周末找个时间QQ【66034278】聊一下 看看对关键词汇的译法 有没有可以调整的 我先试着把你翻译的内容pull过来形成一个单独的branch 试着merge一下 然后再统一pr到原始版本库

发自我的 iPhone

**Comment by jboner** [comment]
So, is this the PR that should be merged? Or is it the other one? Please close the one you don't want merged. Thanks everyone for all the hard work.

**Comment by zzz6519003** [comment]
nothing bro, ignore this one! thx!

2016-02-19 17:22 GMT+08:00 Jonas Bonér <notifications@github.com>:

> So, is this the PR that should be merged? Or is it the other one? Please
> close the one you don't want merged. Thanks everyone for all the hard work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reactivemanifesto/reactivemanifesto/pull/80#issuecomment-186127658>
> .
>



-- 


yours,

正中赵
about.me/zzz6519003
[image: 正中赵 on about.me]
  <http://about.me/zzz6519003>

**Comment by jboner** [comment]
So you mean that this one should be closed and not merged?

**Comment by zzz6519003** [comment]
yep & better be quickly to merge him, cuz there'll be more people do the repetitive work XD

**Comment by pimgeek** [comment]
I agree, also note that https://github.com/rasummer has been idle on github for several months, i don't think a github @ operation will do the magic @jboner 😀

发自我的 iPhone

**Pull request closed without merging**
