### PR TITLE
Correct and clarify Message Driven

### PR DESCRIPTION
**Pull request by projanen**
The first sentence under Message Driven was missing a conjunction.  Additionally, "that ensures...and provides" was unclear due to the large separation and the newly added, nearby "and."  I didn't want to break the sentence into two, but this seemed the clearer way to go.

### CODE REVIEW

**Comment by rkuhn** [comment]
Technically there is no conjunction missing, instead the comma before “and” is superfluous (and incorrect as per Oxford comma rules—since the last part is not the final item of the enumeration). But I agree with the proposal of breaking the sentence up into two, it does make it easier to understand.

While we are fixing this I cannot but notice that the word “errors” is used in error in that same sentence, the point is to delegate “failures” (as explained in the linked glossary entry). Would you mind adding a commit that fixes this? Alternatively I can do that myself after this PR is merged. @jboner do you agree?

**Comment by jboner** [comment]
Yes. Fixed by @ktoso, and merged. Thanks.

**Comment by rkuhn** [comment]
This part has indeed not been done by @ktoso, but now this PR does not merge anymore. I’ll merge it by hand.

**Comment by ktoso** [comment]
Sorry for the misleading link to #66 in that issue :) The wording was "as mentioned in #66" :)

**Comment by lazaridis-com** [comment]
Note that #48 suggests to remove the "Message Driven" part completely (at least from the main traits section). Similar suggestions/rationales given within #73.

**Pull request merged**
