### PR TITLE
add synchronization to description of replication

### PR DESCRIPTION
**Pull request by rkuhn**
See #99 for the discussion that led to this PR.

### CODE REVIEW

**Comment by rkuhn** [comment]
ping @orubel

After this is reviewed and settled we’ll have to ping the contributors of the various translations to add this paragraph to their respective glossaries.

**Comment by rkuhn** [comment]
It would be wonderful if @pbailis or @ept were to chime in and suggest improvements. I am on the fence whether we should use terms a layman can reasonably understand (as in the current proposal) or the more precise but less widely known technical terms to illustrate the possible spectrum of consistency levels.

**Comment by orubel** [comment]
sounds keen. Just a clarification of synchronization of duplicated resources for maintaining state is all that is required.

**Comment by rkuhn** [comment]
Since the original requester as well as Jonas are in favor, and nobody disapproved, I’m going to merge this.

**Comment by jboner** [comment]
Thanks

**Pull request merged**
