### PR TITLE
Added translation of the Reactive Manifesto to Portuguese.

### PR DESCRIPTION
**Pull request by radcortez**

### CODE REVIEW

**Comment by rasummer** [comment]
Hi @radcortez I'm getting ready to add your translation to the Reactive Manifesto website. Could I ask you to translate a small amount of UI elements as well. You can find the phrases that need translation in the following google doc spread sheet: https://docs.google.com/spreadsheets/d/1Z_rA48AWXa1SjyR2n-vGqRKpGk124LtfdbpAOG-38cU/edit?usp=sharing

king regards

Richard

**Comment by radcortez** [comment]
Hi @rasummer, it's done!

Cheers,
Roberto

**Comment by rasummer** [comment]
Thanks @radcortez 

I'll get the translation added next week. Have a good weekend.

**Comment by radcortez** [comment]
No problem. Glad I could help. Let me know if you need anything else.

**Pull request merged**
