### PR TITLE
Replace 耐障害性 with レジリエンス in the Japanese version

### PR DESCRIPTION
**Pull request by eed3si9n**
In #39 I had suggested to use the term "耐障害性", which means fault tolerance, for the translation of "resilience." In light of 'Without Resilience, Nothing Else Matters', which distinguishes resilience from plain fault tolerance, I would like to correct the translation to be "レジリエンス", which is a phonetic transcription of the term resilience.

In the wake of tsunami disasters in Japan, the term "レジリエンス" seems to be catching on in Japan http://www.resilience-jp.org/. I found an writeup called "[リスク対応からレジリアンス強化へ](http://www.jiid.or.jp/ardec/ardec48/ard48_opinion.html)", which has a good overview of the term resilience in the Japanese translation:

> このようにレジリアンスが復元力、強靭性（きょうじんせい）、しなやかさ、抵抗力などのさまざまな総括的意味合いを含む概念であるために、これに一対一で対応できる日本語がなく、英語をカタカナ表記しているのであろう。

It says that the concept of resilience encompasses many meanings such as recoverability, toughness,  suppleness, resistance, and that no term in Japanese matches its meaning one-on-one, and therefore we resort to transcribing it phonetically. Also in the field of psychology they seem to be using [レジリエンス](https://ja.wikipedia.org/wiki/%E3%83%AC%E3%82%B8%E3%83%AA%E3%82%A8%E3%83%B3%E3%82%B9_(%E5%BF%83%E7%90%86%E5%AD%A6)) as well.

/review @okapies, @yugolf

### CODE REVIEW

**Comment by yugolf** [comment]
I agree with your suggestion.
"レジリエンス" is also used on [human](http://online.sbcr.jp/2014/12/003903.html) and [psychology](https://ja.wikipedia.org/wiki/%E3%83%AC%E3%82%B8%E3%83%AA%E3%82%A8%E3%83%B3%E3%82%B9_(%E5%BF%83%E7%90%86%E5%AD%A6)).

I think it will be used commonly on software technology in the near future.

**Comment by okapies** [comment]
I have had a long discussion about this suggestion with @eed3si9n and investigate many candidates. In conclusion, there is no appropriate term for "resilience" in Japanese because of its broader and subtle meaning. Finally, I agree with it. And we need to write blog posts about what レジリエンス means to improve usage in Japanese tech community :)

**Comment by jboner** [comment]
What is the status on this PR?

**Comment by eed3si9n** [comment]
It's been stuck. If someone could merge it that'll be great.

**Comment by jboner** [comment]
@rasummer Merged a fix to the Japanese translation.

**Pull request merged**
