### PR TITLE
Replication creates Cross Cutting Concern (see AOP Principles)

### PR DESCRIPTION
**Pull request by orubel**
Replication of data and/or function does not follow AOP principles and causes a cross cutting concern in the architecture. Proper terminology is 'synchronization whether synchronizing functionality across services from a repository (by copying functionality to all services from same repository) or synchronizing I/O state (by serving state from 'central version of truth' cache/db to subscribing services.

### CODE REVIEW

**Comment by rkuhn** [comment]
Relying on a single central source of truth implies that the system will fail when that source is unavailable. This is fine in many cases (defined by business purpose) or at certain architectural levels (e.g. having one microservice use its own single database). The manifesto takes a larger view and speaks generally, pointing out a farther goal to aspire to: if possible and useful, create systems that do not suffer this failure mode.

**Comment by orubel** [comment]
First... to answer you questions about failure, in a system like that, there is redundancy so a backup can takeover and all I/O state would be synchronized still; failure is caused by application... NOT architecture.

Second, you are confusing 'software as application' ( which is mainly a centralized architecture) with 'architecture as application' (distributed architecture). Distributed systems need to synchronize data at START across all systems and keep that dat in sync or EMNTIRE SYSTEM FAILS; not just one system... entire system. Thats because its a DISTRIBUTED application and thus one point of failure becomes a system wide failure. And not being able to synchronize your I/O across all services is a critical fail. I/O is syncronized across services in centralized systems (one app > one server) so why is this so hard to understand when those services are distributed across different servers? Its still the same approach. I/O still eed to stay in SYNC.

And thats how it should be. If you need to synchronize your code across multiple systems through a repo, the build on ALL will fail or ALL will succeed due to the repo being down; their will be no partial completes because there is no such thing as a partial build in 'architecture as software'

You are confusing 'software as architecture' with 'architecture as software'; just as in software as architecture. all pieces of code must succeed for the build to succeed, all services in architecture must succeed for build to succeed.

And as all services in software need to synchronize I/O or there is a failure, architecture must synchroniz I/O or it fails.

Doing anything otherwise is applying a 'centralized architecture' methodlogy to a 'distributed architecture'.

**Comment by orubel** [comment]
This conversation on state 'syncronization' vs 'replication' can be summed up like this:

- server state is **synchronized** in an architecture through chef, puppet, etc
- code state is **synchronized** in an architecture through repository/artifact repository

All SHARED systems are synchronized... not duplicated; duplication does occur as an effect of the synchronizations but they stay in sync because a single system and/or single file keeps them in sync.

This make more sense now? I'm merely talking about the difference between 'synchronization' vs 'duplication' and how the word 'synchronization' has an improved connotation over 'duplication which is archaic in a modern distributed system.

**Comment by orubel** [comment]
So if we want to maintain I/O state across all machines, you cannot merely duplicate all information related to endpoint data to all machines, you must also SYNCHRONIZE said data. Duplicate without synchronization leads to 'cross cutting concerns' and in distributed systems, leads to 'architectural cross cutting concerns' related to I/O : https://www.slideshare.net/bobdobbes/university-of-washington-the-new-api-pattern#14

Hence, the wording of 'synchronization' vs 'duplication' is VERY significant. Because if you merely say 'duplication', you are promoting a cross cutting concern in your code.

**Comment by rkuhn** [comment]
Now it is clear what you mean, and I agree that haphazard duplication is not what we promote: does replication in a technical context not typically entail the dissemination of updates? The word «synchronization» is problematic in this context since its connotations from multithreading exclude eventually consistent approaches—which is due to its literal meaning. Resilient systems can be built in many ways and the choice of consistency level for distributed data handling is key for achieving the appropriate level of availability.

My proposal is to improve the glossary entry for replication by including the need to keep replicas in sync, giving a few examples of suitable mechanisms.

**Comment by orubel** [comment]
Cool. I can be cool with that. Keeping state, data and functionality in sync is all I'm pushing for in the doc :)

**Comment by rkuhn** [comment]
superseded by #100

**Pull request closed without merging**
