### PR TITLE
Swahili version of reactive manifesto

### PR DESCRIPTION
**Pull request by hungaikev**
Work is done by @ianbwana and myself (@hungaikev)

### CODE REVIEW

**Comment by hungaikev** [comment]
Completed the swahili transtion @jboner

**Comment by jboner** [comment]
Awesome job. Thanks a lot. 
@rasummer Can you publish this PR when you have time?

**Comment by rasummer** [comment]
Sure, I'll put some time aside next week.

**Comment by jboner** [comment]
Thanks a lot.

**Pull request merged**
