### PR TITLE
Fix Russian translation

### PR DESCRIPTION
**Pull request by ihostage**
@agolubev please review. This is small changes, that we discussed in
https://github.com/reactivemanifesto/reactivemanifesto/pull/120#discussion_r249121684

### CODE REVIEW

**Comment by ihostage** [comment]
Hi, Jonas @jboner! 👋 
Can you merge it?

**Comment by jboner** [comment]
It's not that I don't trust you, but the process needs me to find someone to review the PR. And I don't read Russian. Asked around now. Stay tuned. Sorry for the late response. I missed this one for some reason.

**Comment by agolubev** [comment]
`Responsiveness` is translated as `С допстимым/минимальным временем отклика`. Microsoft is translating this way as well as Russian scientific literature

**Comment by jboner** [comment]
Thanks a lot for the contribution.

**Comment by jboner** [comment]
@rasummer Make sure to include this merged PR when you deploy next time. Thanks.

**Comment by rasummer** [comment]
Will do

**Comment by ihostage** [comment]
Thank a lot, Jonas @jboner! 👍

**Pull request merged**
