### PR TITLE
Update Turkish translation for Reactive Manifesto

### PR DESCRIPTION
**Pull request by bdaylik**
This pull request aims to improve Turkish translation. It does not include Glossary.

### CODE REVIEW

**Comment by jboner** [comment]
Thanks a lot. Much appreciated.

**Comment by rasummer** [comment]
@fehmicansaglam Could you be kind enough to also translate the UI elements that we use on the manifesto website. The following spreadsheet outlines the terms we need: https://docs.google.com/spreadsheets/d/1Z_rA48AWXa1SjyR2n-vGqRKpGk124LtfdbpAOG-38cU/edit?usp=sharing

regards

Richard

**Comment by fehmicansaglam** [comment]
Sure.

**Comment by fehmicansaglam** [comment]
@rasummer done.

**Comment by rasummer** [comment]
@fehmicansaglam thank you

**Pull request merged**
