### PR TITLE
Correct pt-BR translation

### PR DESCRIPTION
**Pull request by megazord**
I've also correct small typos at the google docs spreadsheet.

### CODE REVIEW

**Comment by megazord** [comment]
@igorcosta since you did the original translation, fell free to comment on this PR. :-)

**Comment by cadocruz** [comment]
@megazord, good work.

**Comment by megazord** [comment]
Could someone take a look here in order to integrate this PR? The current pt-BR translation has a lot of errors.

**Comment by igorcosta** [comment]
Everything depends on single point of view. @megazord  you did a good job.

**Comment by jboner** [comment]
Is it ready to go?

**Comment by megazord** [comment]
@jboner Yep!

**Comment by jboner** [comment]
Great. Thanks a lot. @rasummer

**Comment by marcospereira** [comment]
@jboner any idea about when it will be updated on website?

**Comment by jboner** [comment]
When @rasummer or @jroper will get a chance to push it.

**Comment by jroper** [comment]
@marcospereira these fixes need to be copied to

https://github.com/reactivemanifesto/website-manifesto/blob/master/app/views/ptBR/manifesto.scala.html

They also need to be made on the PDF.  @rasummer usually does this stuff, I'm not sure what his process is.

**Comment by rasummer** [comment]
I may have time later today to make both the HTML and PDF changes, if not then it will be early next week.

**Comment by marcospereira** [comment]
@rasummer and @jroper thanks!

**Pull request merged**
