### PR TITLE
Update the Chinese translation of the Reactive Menifesto

### PR DESCRIPTION
**Pull request by hepin1989**
After a long time collaboration and we have finally done with it. The translation I PRed here is a part of the book *Reactive Design Patterns*'s Chinese version 《反应式设计模式》。

Hope this collaboration will help and reduce the *surprise* and *inconsistency*.

### CODE REVIEW

**Comment by hepin1989** [comment]
cc @rkuhn @jboner @ktoso , so @neomaclin @Hawstein @WayneWang12 @cjuexuan looking forward for your input.

**Comment by hepin1989** [comment]
The previous translation **响应式** is heavily affected by the **Responsive web appliance development** which translated to **响应式Web应用程序开发** means that a layout of a webpage could re-layout one you resize the window. That is definitely not what we talking about the *Reactive* there. So The translation of *Reactive* to *响应式* is totally wrong。

**Comment by jboner** [comment]
Awesome. Thanks a lot for your hard work. Very much appreciated.

**Comment by jboner** [comment]
@rasummer Hey Rich, can you push this up to the site when you have time? Thanks a lot.

**Comment by hepin1989** [comment]
Thank you very much 💯

**Comment by hepin1989** [comment]
@rasummer Will you have anytime to update it? Thank you:).

**Comment by rasummer** [comment]
@jboner @hepin1989 On my list to do it this week.

**Comment by hepin1989** [comment]
@rasummer Yes，the header title should be change too,thanks a lot.
image
Should be **反应式宣言**

**Comment by WayneWang12** [comment]
Seems nowhere in this repository we can do this change. Can you help us to update it? @rasummer

**Comment by hepin1989** [comment]
The translation in the picture should be changed too, or just keep the same as the English one.

**Comment by rasummer** [comment]
@WayneWang12 @hepin1989 

If you could take a look at this file in the website repo: https://github.com/reactivemanifesto/website-manifesto/blob/master/conf/messages.zh-CN

Please translate anything remaining that is incorrect and send a PR. 

thanks

**Comment by WayneWang12** [comment]
@rasummer I see. I'll make a pr soon. Thank you! :)

**Pull request merged**
