### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tobybaier**
Responsive, resilient and elastic are brilliant design principles of which requirements can be derived. But "message-driven" is a solution to a part of these plus others. It just doesn't fit, it is a category mistake. It's a "how", not a "what". Remove it and it's wonderful. You still can advocate for message driven communication between loosly coupled micro systems or whatever, but is not on the same level as the other three. If we come up with a better way of achieving what we want to achieve with message driven architectures at the moment, like, say, neuronal one-way-high-speed connections or whatever, then responsive, resilient and elastic still make sense.

### CODE REVIEW

**Comment by rkuhn** [comment]
Hmm, what happened here? I’m pretty certain that I commented yesterday before manually merging this into master. But maybe I commented in the wrong place?

Anyway, this change is in.

**Comment by rkuhn** [comment]
Aargh,

**Comment by lazaridis-com** [comment]
This affects / is a duplicate of #48

**Comment by jboner** [comment]
Simply removing it won't work. We have discussed this in the past and have some ideas. But it would require a 3.0, which is problematic now with almost 20K signatories and 12 language translations.

**Pull request closed without merging**
