### PR TITLE
WIP,DO NOT MERGE,Update the Chinese version's translation.

### PR DESCRIPTION
**Pull request by hepin1989**
As we (@Hawstein @scweang and me) are currently translating the `Reactive Design Patterns` to Chinese for [tsinghua press](http://www.tup.tsinghua.edu.cn/index.html), we must do some update here, as the contents is also a part of appendix C/

### CODE REVIEW

**Comment by jboner** [comment]
@hepin1989 What's the status for this PR?

**Comment by jboner** [comment]
Closing this due to inactivity.

**Comment by hepin1989** [comment]
@jboner This version is OK , but not the final version. When I found time ,will give a finial version.

**Comment by hepin1989** [comment]
Will resubmit a PR soon.

**Pull request closed without merging**
