### PR TITLE
Italian translation for Reactive Manifesto

### LINKED ISSUE #56: Italian translation of the Manifesto
Hi, I have translated README.md and glossary.md files to Italian... hope this helps.

I will issue a pull-request

### PR DESCRIPTION
**Pull request by csparpa**
This is intended to fix #56

### CODE REVIEW

**Comment by jboner** [comment]
Thank you very much. Great job. Can you squash your commits and I'll merge it?

**Comment by csparpa** [comment]
Squashed and now mergeable. Thanks Jonas

**Comment by jboner** [comment]
Great. Thanks.

**Comment by csparpa** [comment]
Welcome, I will add an issue on the Manifesto website repository to ask for Italian translation embedding.

**Pull request merged**
