### PR TITLE
fix typo in cn version of glossary

### PR DESCRIPTION
**Pull request by cuipengfei**
fix typo in glossary.zh-cn

### CODE REVIEW

**Comment by cuipengfei** [comment]
@pimgeek   @hepin1989

**Comment by hepin1989** [comment]
Yes,thanks

**Comment by cuipengfei** [comment]
@jboner  please help to merge

**Comment by jboner** [comment]
@rasummer Can you do a push of this when you get the time?

**Comment by rasummer** [comment]
This has been updated on the website

**Pull request merged**
